### ISSUE TITLE
[Loading] Add a loading screen inbetween playlist and parameter screen

### ISSUE THREAD

**Issue by ziyi01** [dynamisk-webb/Gold-Digger#11]
**Loading** tasks:
- [x] Presenter
- [x] Include Audio player (with Elevator music 🎵)
- [x] Logic/Algorithm
    - [x] Implement API call (Get playlist)
    - [x] Filter from parameters 
    - [x] Handle case when filtering leaves us with empty list
- [x] Set generated in model
- [x] Go to next screen (navigation)

**Comment by ziyi01** [comment]
Refer to #7, might need to add functionality to auto-play from presenter (since it is not allowed to auto-play on render).

**Comment by gorwat** [comment]
Skeleton code exists and previous todos have been cleaned up (commit 66f9d54)
