### ISSUE TITLE
[Source] Input box for Playlist URL

### ISSUE THREAD

**Issue by ziyi01** [dynamisk-webb/Gold-Digger#12]
Use an input box instead of button to input spotify playlist url. Use onEnter to submit.

Sets source playlist.

**Comment by Fetaost-code** [comment]
View side is in order, sending url to: **props.setSource(url);**
![YesSirYesBossGIF](https://user-images.githubusercontent.com/74512132/233330882-4a15780d-f4a0-4929-990b-40e4c71a9bda.gif)

**Comment by Kramkavalkad** [comment]
https://github.com/dynamisk-webb/Gold-Digger/security/dependabot
 
 presentersidan borde vara klar nu!
