### ISSUE TITLE
[Playlist] Remove track and save to playlist button

### ISSUE THREAD

**Issue by ziyi01** [dynamisk-webb/Gold-Digger#23]
In playlistview. It is a party!

It will require:
- [x] Sync with Firebase
- [x] Remove from DiggerModel
- [x] Delete button (View --> Presenter)

**Comment by Fetaost-code** [comment]
remove button added to view

**Comment by gorwat** [comment]
There's no remove fn for a single track in a generated list in diggerModel (on main at least), however there is one for removing previous playlists. Mixup? I am adding a placeholder fn with a name and nothing more in diggerModel for now

**Comment by ziyi01** [comment]
Oops, it was on my local machine. I'll resolve conflicts and add it.

**Comment by Fetaost-code** [comment]
Has been added in Playlist branch

**Comment by Fetaost-code** [comment]
And now added to main. Doesn't work right now due to rendering of a fixed playlist
