### ISSUE TITLE
[Firebase] Assign firebasekey based on total generated lists

### ISSUE THREAD

**Issue by gorwat** [dynamisk-webb/Gold-Digger#34]
- [ ] Create a new model parameter to keep track of how many playlists the user has created
- [ ] Increment said parameter whenever a new playlist is generated and set  current value of parameter as the generated list's firebaseKey
- [ ] Update persistence functions to include parameter

**Comment by ziyi01** [comment]
Isn't it possible to use ``length`` with the ``prevPlaylists`` parameter for this:
```javascript
   generated.firebaseKey = prevPlaylists.length;
   // persistence function
``` 
Since we should persist the previous playlists either way.

**Comment by gorwat** [comment]
Not if we want to give the user the option to remove previously generated playlists. Talked irl about moving the counter to firebasemodel
