### ISSUE TITLE
[Playlist] Make the playlist name editable

### ISSUE THREAD

**Issue by Fetaost-code** [dynamisk-webb/Gold-Digger#38]
The playlist name should be editable

**Comment by ziyi01** [comment]
``changePlaylistName`` in ``spotifySource.js`` is where you should check for api calls btw!

**Comment by gorwat** [comment]
I have a low effort fix for this (changes name in model every letter you write) over at branch persist-firebase as I needed to check if firebase updated correctly. Note that it does not update the name of the actual spotify-list if the user has added it to their account (the call Julia mentioned)

**Comment by gorwat** [comment]
Diggermodel fn also only update the name that is stored in the current generated object, not the name that is stored in the prevGeneratedList which also needs to be fixed
