### ISSUE TITLE
[Search] Ensure the search for both artists and genres work

### ISSUE THREAD

**Issue by Fetaost-code** [dynamisk-webb/Gold-Digger#42]

**Comment by ziyi01** [comment]
Genre search finished in [commit](https://github.com/dynamisk-webb/Gold-Digger/commit/9a724fe80c1aadccd48264a58d71474bef636e3b)

**Comment by Fetaost-code** [comment]
Artist search finished in [pull request](https://github.com/dynamisk-webb/Gold-Digger/pull/59)
