### ISSUE TITLE
[Playlist] Get playlist from persistence

### ISSUE THREAD

**Issue by gorwat** [dynamisk-webb/Gold-Digger#46]
In the lifecycle in /playlist a generated playlist needs to be fetched from persistance based on the firebaseKey of the current generated playlist. This will be a promise that needs to be resolved, including suspense.

**Comment by Kramkavalkad** [comment]
Some progress made. Resolving promise form firebase, stuff added to branch 'playlistPresenter'

**Comment by gorwat** [comment]
Solved with #53
