### ISSUE TITLE
[Source] Redirects despites errors

### ISSUE THREAD

**Issue by ziyi01** [dynamisk-webb/Gold-Digger#56]
Move navigate in sourceView to presenter so you can check errors? If this hasn't already been fixed

**Comment by Fetaost-code** [comment]
I dont think it redirects in the case of invalid URL at least?

**Comment by ziyi01** [comment]
It was mostly about the issue of XHR-errors passing and it still redirecting to GenreView like @gorwat mentioned during the meeting on Monday.
