### ISSUE TITLE
[Previous session] Redirect bug

### ISSUE THREAD

**Issue by Kramkavalkad** [dynamisk-webb/Gold-Digger#63]
DID
Start at /home. Navigate to "previous session" by pressing that button. 
Then press back arrow.

HAPPENS
User is transported to /source.

EXPECTED
Go back to the previous page, i.e. /home

**Comment by Fetaost-code** [comment]
Hmm oklart om det är en bug och mer att det kanske bör finnas knapp för att återvända hem. När man går genom stegen bör < ta en till steget innan tänker jag

**Comment by ziyi01** [comment]
It depends, if it is desireable to go to previous page only then we have to change returnACB in filterView to ``navigate(-1)`` which I think had a bug when we tested it last time.

**Comment by Fetaost-code** [comment]
yeah, navigate(-1) always leads you back to the previous page, regardless if it was on the site or not 😅 I could add a home button to layoutView!

**Comment by gorwat** [comment]
Home redirect is an excellent addition. However, the back button from /genre should not lead to /source if we have continued from a precious session in my opinion as it caused great confusion during testing. Is there a problem with using navigate(-1) in that particular case?

**Comment by Fetaost-code** [comment]
Fixed with an alternative solution. Additional button navigating from source --> home
