### ISSUE TITLE
[Artists] Long loading times on long playlists

### ISSUE THREAD

**Issue by Fetaost-code** [dynamisk-webb/Gold-Digger#78]
- The loading icon gets stuck when loading the artists (towards the end)
- Including or excluding an artists has a loading time (shouldn't have)
- Searching for "" takes a lot of time (should be instant?)

**Comment by ziyi01** [comment]
Might be better to splice the list and only display 100 at a time

**Comment by ziyi01** [comment]
Can also be that we need to also call firebase as well

**Comment by ziyi01** [comment]
Partially handled by using Promises.all when getting the track lists and also lowering image resolutions
