### ISSUE TITLE
[Parameter] Add tool tips to Parameter View

### ISSUE THREAD

**Issue by ziyi01** [dynamisk-webb/Gold-Digger#8]
MUI tool tip API: https://mui.com/material-ui/react-tooltip/

Add to explain each parameter.

**Comment by Fetaost-code** [comment]
Has been added, with commit: [23f5c150c3e2c3bb02afff153cf21318f23b4472](https://github.com/dynamisk-webb/Gold-Digger/commit/23f5c150c3e2c3bb02afff153cf21318f23b4472)
